spring:
  application:
    name: listing-service

  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME:RoomRental}?currentSchema=${SCHEMA_NAME:listing_booking_service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  liquibase:
    enabled: true
    default-schema: ${SCHEMA_NAME:listing_booking_service}
    liquibase-schema: ${SCHEMA_NAME:listing_booking_service}

  jpa:
    hibernate:
      ddl-auto: none